import { Product } from "./store";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Beaumont Summit",
    price: 3300,
    originalPrice: 4500,
    image: "/img/product/1.jpg",
    category: "women",
    rating: 3,
    inStock: true,
    description: "Elegant jewelry piece with exquisite craftsmanship.",
  },
  {
    id: "2",
    name: "Classic Gold Ring",
    price: 4000,
    image: "/img/product/2.jpg",
    category: "women",
    rating: 4,
    inStock: true,
  },
  {
    id: "3",
    name: "Pearl Necklace",
    price: 3000,
    originalPrice: 4500,
    image: "/img/product/3.jpg",
    category: "women",
    rating: 5,
    inStock: true,
  },
  {
    id: "4",
    name: "Diamond Earrings",
    price: 6000,
    image: "/img/product/4.jpg",
    category: "women",
    rating: 4,
    inStock: true,
  },
  {
    id: "5",
    name: "Silver Bracelet",
    price: 3500,
    originalPrice: 4500,
    image: "/img/product/5.jpg",
    category: "women",
    rating: 3,
    inStock: true,
  },
  {
    id: "6",
    name: "Rose Gold Set",
    price: 4500,
    image: "/img/product/6.jpg",
    category: "women",
    rating: 4,
    inStock: true,
  },
  {
    id: "7",
    name: "Art Deco Pendant",
    price: 5500,
    image: "/img/product/7.jpg",
    category: "women",
    rating: 5,
    inStock: true,
  },
  {
    id: "8",
    name: "Vintage Brooch",
    price: 2000,
    originalPrice: 5500,
    image: "/img/product/8.jpg",
    category: "women",
    rating: 3,
    inStock: true,
  },
];
